name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Build backend image
      run: docker build -t capstone-backend ./backend

    - name: Install Trivy
      run: |
        sudo apt-get update
        sudo apt-get install -y gnupg lsb-release curl
        curl -fsSL https://aquasecurity.github.io/trivy-repo/deb/public.key \
          | sudo gpg --dearmor -o /usr/share/keyrings/trivy.gpg
        echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -cs) main" \
        | sudo tee /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install -y trivy


    - name: Trivy scan backend image
      run: |
        trivy image capstone-backend:staging \
          --severity HIGH,CRITICAL \
          --no-progress \
          --exit-code 0


    - name: Build frontend image
      run: docker build -t capstone-frontend ./frontend

    - name: Run backend unit tests
      run: docker run --rm capstone-backend pytest tests -v
