name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Trivy scan (backend image)
      uses: aquasecurity/trivy-action@master
      with:
          image-ref: capstone-backend
          severity: CRITICAL,HIGH
          exit-code: 0

    - name: Build backend image
      run: docker build -t capstone-backend ./backend

    - name: Build frontend image
      run: docker build -t capstone-frontend ./frontend

    - name: Run backend unit tests
      run: docker run --rm capstone-backend pytest tests -v
