name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Build backend image
      run: docker build -t capstone-backend ./backend

    - name: Install Trivy
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.68.1_Linux-64bit.deb
        sudo dpkg -i trivy_0.68.1_Linux-64bit.deb

    - name: Trivy scan backend image
      run: |
        trivy image capstone-backend:staging \
          --severity HIGH,CRITICAL \
          --no-progress \
          --exit-code 0


    - name: Build frontend image
      run: docker build -t capstone-frontend ./frontend

    - name: Run backend unit tests
      run: docker run --rm capstone-backend pytest tests -v
